name: Weekly Stock Price Crawler

on:
  schedule:
    - cron: '0 7 * * 5'  # Every Friday at 3PM GMT+8 (GMT = UTC+0, so 3PM GMT+8 = 7AM UTC)
  workflow_dispatch:     # Allow manual trigger via GitHub UI

permissions:
  contents: write         # ✅ Allow pushing commits

jobs:
  crawl:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run crawler
        run: python stock_crawler.py

      - name: Commit and push CSV
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add data/stock_prices.csv
          git commit -m "Update stock prices on $(date +'%Y-%m-%d')" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
