name: Weekly Stock Price Crawler

on:
  schedule:
    - cron: '0 7 * * 5'  # Every Friday at 3PM GMT+8 (7AM UTC)
  workflow_dispatch: {}

jobs:
  crawl:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Allow workflow to push changes

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
          persist-credentials: false  # We'll use GITHUB_TOKEN instead

    - name: Log current time
      run: |
        echo "Workflow triggered at: $(date -u)"

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run crawler
      run: python stock_crawler.py

    - name: Commit changes
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add .
        git commit -m "Update stock prices on $(date '+%Y-%m-%d %H:%M:%S')" || echo "No changes to commit"

    - name: Set remote URL with token
      run: |
        git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/hkean/stock-crawler.git

    - name: Push changes
      run: git push
