name: Crawl Stock Prices

on:
  schedule:
    - cron: '0 7 * * 5' # Every Friday at 3 PM GMT+8 (which is 7 AM UTC)
  workflow_dispatch: # Optional: allows manual run

jobs:
  run-crawler:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install yfinance pandas

      - name: Run stock crawler
        run: python stock_crawler.py

      - name: Upload output CSV as artifact
        uses: actions/upload-artifact@v4
        with:
          name: stock-prices
          path: stock_prices.csv
