name: Weekly Stock Price Crawler

on:
  schedule:
    - cron: '0 7 * * 5'  # Every Friday 3PM GMT+8
  workflow_dispatch:

permissions:
  contents: write  # ✅ allow commit and push to repo

jobs:
  crawl:
    runs-on: ubuntu-latest
